### ISSUE TITLE
[Feature Request] Add 2FA support

### ISSUE THREAD

**Issue by jaafarabazid** [WP-Busters/passwordless-wp#1]
Hi,

Thank you for the great plugin you have developed. It helps to secure WordPress accounts and make our lives much easier.

But to make your plugin a perfect one, especially for those who don't have physical authenticators, I suggest adding support for 2FA. This will make your plugin richer and acts as an extra solid security layer for the WordPress login.

I know that there are some other plugins that support 2FA, like [Two Factor](https://wordpress.org/plugins/two-factor). but no one likes to install many plugins, especially for those that serve the same purpose. And having one plugin that supports FaceID, TouchID, and 2FA will make it a game-changer in this field.

Wish you all the best.

**Comment by fnpen** [comment]
@abazeed Thank you for your idea, I will think about it.
I think now it's one feature plugin. If I add more features it will require more other things, which I should support and it's supported by other plugins.
