### ISSUE TITLE
Can't create credentials

### ISSUE THREAD

**Issue by deepseek-ai-chat** [WP-Busters/passwordless-wp#2]
The plugin doesn't let create credentials, screencast - https://take.ms/cESdp

After removing the plugin doesn't work login through a standard wordpress form. Only through wp_set_auth_cookie().

How to remove the plugin completely?

**Comment by fnpen** [comment]
@egmalt Thank you for your message, the plugin does not modify or change standard WordPress form,
I will be happy to look deeper, I see your another message, please reply on it.
